NextAuth Sign-in + forgot password flow
calblueprint/ogsc pull request #172
Opened 2021-03-07 06:05 UTC by joyydong

# Sign-in and Forgot Password Flow

Started sign in process (doesn't authorize correctly atm) and forgot password flow (send email > reset password)

## TODO (if applicable)

- [ ] Figure out sign in authorization
- [ ] Email address on reset password page?
- [ ] (if applicable) Error pages for the reset password page

## How to Test/Use PR feature
### Sign In
- go to http://localhost:3000/auth/signin and sign in (using an account that has been authorized or admin@ogsc.dev)
 ### Forgot Password Flow
- go to http://localhost:3000/auth/forgotPassword and enter email of an account that has been authorized
- go to http://localhost:3000/auth/passwordRecovery?resetCode=RESETCODEID
- enter new password and reset password
- verify in ResetPassword table that `isUsed` is now `true` && in Users table that `hashedPassword` value has been updated

## PR Checklist

Does your branch (check if true):
- [ ] work when you run `yarn build`? 
_still WIP_
- [x] successfully run `yarn:db-migrate up` without yielding any errors?
- [x] successfully run `yarn prisma introspect` without yielding any errors?
- [ ] successfully run `yarn dev` and support all changes that your branch intends to perform?
_still WIP_

## Screenshots
Sign In
<img width="1402" alt="Screen Shot 2021-03-06 at 9 56 32 PM" src="https://user-images.githubusercontent.com/34170094/110230577-d3fb0580-7ec6-11eb-95b4-b49a5c11d484.png">

Forgot Password
<img width="1364" alt="Screen Shot 2021-03-06 at 10 02 57 PM" src="https://user-images.githubusercontent.com/34170094/110230729-baa68900-7ec7-11eb-9c56-229e5aed099e.png">
(reset code in email field is a placeholder)
<img width="1306" alt="Screen Shot 2021-03-06 at 10 03 44 PM" src="https://user-images.githubusercontent.com/34170094/110230752-d90c8480-7ec7-11eb-8b37-b5a8b66adbd3.png">

CC: @sydbui

2021-03-15 04:06 UTC, sydbui requested changes

2021-03-15 04:06 UTC, sydbui commented on pages/auth/passwordRecovery/confirmation.tsx
> +            <Link href="/admin/players">
this might want to be /api/auth/signin bc they aren't signed in yet

2021-03-15 04:06 UTC, sydbui commented on pages/auth/signin.tsx
> +        callbackUrl: `${window.location.origin}/admin/players`,
change "admin" to whatever type of user is signed in — you can usually do this by using useSession — though I am not sure if you can do that here with nextAuth but try it out! if not lmk :)

2021-04-03 18:44 UTC, sydbui requested changes
found a couple of bugs and left one comment about it. First is that an error is thrown when you try to sign in with a user that is not an admin so I think the redirecting maybe have an issue. Next, when you do get redirected (signing in as an admin) the page doesn't actually load until you click on the url itself (idk if that made sense but I can show you as well)! GREAT JOB JOY :))))) TY

2021-04-03 18:44 UTC, sydbui commented on pages/index.tsx
> +        const role = data?.user.roles[0].type;
this line seems to throw and error when you try to sign in as anything other than an admin user

2021-04-10 00:38 UTC, rlhe811 commented
Hello!
Sign In Page:
- same note from the create account flow for the "Show Password" toggle
- can the "create an account here" link be semi-bolded + show an underline on hover?

Forgot Password Page:
- Can we actually put the instruction text above the field? (similar to the instructional text on the for the note to admin field on the create account flow)

New Password Page:
- same note from the create account flow for the "Show Password" toggle

Error Page:
- can the "new password reset" link also be semi-bolded + show an underline on hover? (just to clarify only the blue link should be bolded not the grey part)

TY JOY :D

2021-04-10 01:21 UTC, rlhe811 commented
OH i forgot to mention this but it would b great to have focus states for all the blue buttons that look like this
<img width="483" alt="Screen Shot 2021-04-09 at 6 10 55 PM" src="https://user-images.githubusercontent.com/46945934/114253764-69733480-9960-11eb-8c01-e1ad17db8760.png">
there's a 15% opacity white overlay on it :))

2021-04-12 02:01 UTC, merged